[2024-01-07T13:54:16.711+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T13:54:16.726+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T13:54:16.726+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T13:54:16.753+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T13:54:16.761+0000] {standard_task_runner.py:57} INFO - Started process 1025 to run task
[2024-01-07T13:54:16.766+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp2vfxfoky']
[2024-01-07T13:54:16.770+0000] {standard_task_runner.py:85} INFO - Job 251: Subtask copy_country_Postgres_To_GCS
[2024-01-07T13:54:16.849+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T13:54:17.008+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T13:54:17.024+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:54:17.039+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:54:17.063+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T13:54:17.070+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T13:54:17.071+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T13:54:17.089+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T135416, end_date=20240107T135417
[2024-01-07T13:54:17.141+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T13:54:17.172+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T15:52:57.492+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:52:57.511+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:52:57.511+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T15:52:57.538+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T15:52:57.548+0000] {standard_task_runner.py:57} INFO - Started process 4265 to run task
[2024-01-07T15:52:57.553+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpoiozy4sl']
[2024-01-07T15:52:57.560+0000] {standard_task_runner.py:85} INFO - Job 356: Subtask copy_country_Postgres_To_GCS
[2024-01-07T15:52:57.654+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T15:52:57.811+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T15:52:57.829+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:52:57.846+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:52:57.874+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T15:52:57.882+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T15:52:57.920+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T15:52:57.929+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T15:52:59.993+0000] {gcs.py:576} INFO - Data stream uploaded to data/country-{ds_nodash}.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T15:53:00.020+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T15:53:00.111+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:53:00.132+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T15:53:00.133+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T15:53:00.162+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T155257, end_date=20240107T155300
[2024-01-07T15:53:00.259+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T15:53:00.297+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T15:58:23.268+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:58:23.292+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:58:23.292+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T15:58:23.317+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T15:58:23.324+0000] {standard_task_runner.py:57} INFO - Started process 4432 to run task
[2024-01-07T15:58:23.329+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '364', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpxhkxmrud']
[2024-01-07T15:58:23.337+0000] {standard_task_runner.py:85} INFO - Job 364: Subtask copy_country_Postgres_To_GCS
[2024-01-07T15:58:23.426+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T15:58:23.591+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T15:58:23.610+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:58:23.628+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:58:23.653+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T15:58:23.658+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T15:58:23.683+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    date = {{ ds_nodash }}
NameError: name 'ds_nodash' is not defined
[2024-01-07T15:58:23.721+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T155823, end_date=20240107T155823
[2024-01-07T15:58:23.742+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T15:58:23.742+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T15:58:23.742+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T15:58:23.756+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T15:58:23.757+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T15:58:23.758+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    date = {{ ds_nodash }}
NameError: name 'ds_nodash' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T15:58:23.915+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 364 for task copy_country_Postgres_To_GCS (name 'ds_nodash' is not defined; 4432)
[2024-01-07T15:58:23.941+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T15:58:23.981+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T16:05:56.777+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T16:05:56.821+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T16:05:56.821+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T16:05:56.953+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T16:05:56.962+0000] {standard_task_runner.py:57} INFO - Started process 4660 to run task
[2024-01-07T16:05:56.968+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpzdwm84bo']
[2024-01-07T16:05:56.974+0000] {standard_task_runner.py:85} INFO - Job 374: Subtask copy_country_Postgres_To_GCS
[2024-01-07T16:05:57.061+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T16:05:57.201+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T16:05:57.220+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:57.234+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:57.266+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T16:05:57.272+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T16:05:57.306+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T16:05:57.315+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T16:05:59.438+0000] {gcs.py:576} INFO - Data stream uploaded to data/country-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T16:05:59.452+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T16:05:59.491+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:59.507+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T16:05:59.508+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T16:05:59.526+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T160556, end_date=20240107T160559
[2024-01-07T16:05:59.593+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T16:05:59.625+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T17:53:16.374+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T17:53:16.411+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T17:53:16.411+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T17:53:16.451+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T17:53:16.458+0000] {standard_task_runner.py:57} INFO - Started process 7257 to run task
[2024-01-07T17:53:16.462+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '384', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpiiqs_vpb']
[2024-01-07T17:53:16.466+0000] {standard_task_runner.py:85} INFO - Job 384: Subtask copy_country_Postgres_To_GCS
[2024-01-07T17:53:16.557+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T17:53:16.715+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T17:53:16.736+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T17:53:16.755+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T17:53:16.776+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T17:53:16.781+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T17:53:16.814+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T17:53:16.820+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T17:53:18.978+0000] {gcs.py:576} INFO - Data stream uploaded to data/country-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T17:53:18.996+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T17:53:19.022+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T17:53:19.041+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T17:53:19.041+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T17:53:19.062+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T175316, end_date=20240107T175319
[2024-01-07T17:53:19.165+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T17:53:19.210+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T18:01:22.522+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T18:01:22.552+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T18:01:22.553+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T18:01:22.576+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T18:01:22.588+0000] {standard_task_runner.py:57} INFO - Started process 7497 to run task
[2024-01-07T18:01:22.602+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '395', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp62nbcx6p']
[2024-01-07T18:01:22.606+0000] {standard_task_runner.py:85} INFO - Job 395: Subtask copy_country_Postgres_To_GCS
[2024-01-07T18:01:22.904+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T18:01:23.472+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T18:01:23.491+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T18:01:23.508+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T18:01:23.536+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T18:01:23.542+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T18:01:23.587+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T18:01:23.593+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T18:01:25.674+0000] {gcs.py:576} INFO - Data stream uploaded to data/country-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T18:01:25.686+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T18:01:25.710+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T18:01:25.725+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T18:01:25.726+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T18:01:25.741+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T180122, end_date=20240107T180125
[2024-01-07T18:01:25.827+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T18:01:25.851+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:12:27.551+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:12:27.661+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:12:27.661+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:12:27.902+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T19:12:27.909+0000] {standard_task_runner.py:57} INFO - Started process 9372 to run task
[2024-01-07T19:12:27.914+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '412', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpvnsrg0ja']
[2024-01-07T19:12:27.918+0000] {standard_task_runner.py:85} INFO - Job 412: Subtask copy_country_Postgres_To_GCS
[2024-01-07T19:12:28.237+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:12:28.931+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T19:12:28.962+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:12:29.013+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:12:29.044+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:12:29.055+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:12:29.056+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:12:29.074+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T191227, end_date=20240107T191229
[2024-01-07T19:12:29.632+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:12:29.663+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:13:41.827+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:13:41.856+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:13:41.857+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:13:41.890+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T19:13:41.898+0000] {standard_task_runner.py:57} INFO - Started process 9430 to run task
[2024-01-07T19:13:41.901+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '419', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp3b4tuytk']
[2024-01-07T19:13:41.904+0000] {standard_task_runner.py:85} INFO - Job 419: Subtask copy_country_Postgres_To_GCS
[2024-01-07T19:13:41.976+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:13:42.129+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T19:13:42.149+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:13:42.162+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:13:42.181+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:13:42.249+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:13:43.159+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T19:13:43.166+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T19:13:45.145+0000] {gcs.py:576} INFO - Data stream uploaded to data/country-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T19:13:45.160+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T19:13:45.192+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:13:45.214+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:13:45.215+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:13:45.233+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T191341, end_date=20240107T191345
[2024-01-07T19:13:45.295+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:13:45.336+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:30:36.875+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:30:36.887+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:30:36.887+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:30:36.914+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T19:30:36.924+0000] {standard_task_runner.py:57} INFO - Started process 9931 to run task
[2024-01-07T19:30:36.928+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '438', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp5c46_48w']
[2024-01-07T19:30:36.931+0000] {standard_task_runner.py:85} INFO - Job 438: Subtask copy_country_Postgres_To_GCS
[2024-01-07T19:30:37.024+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:30:37.178+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T19:30:37.196+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:30:37.214+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:30:37.232+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:30:37.294+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:30:37.667+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T19:30:37.674+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T19:30:39.490+0000] {gcs.py:576} INFO - Data stream uploaded to data/country-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T19:30:39.508+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T19:30:39.599+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:30:39.750+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:30:39.750+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:30:39.774+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T193036, end_date=20240107T193039
[2024-01-07T19:30:39.917+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:30:40.002+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:58:51.436+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:58:51.468+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:58:51.468+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:58:51.502+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T19:58:51.513+0000] {standard_task_runner.py:57} INFO - Started process 10685 to run task
[2024-01-07T19:58:51.518+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '458', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp5epmok1r']
[2024-01-07T19:58:51.522+0000] {standard_task_runner.py:85} INFO - Job 458: Subtask copy_country_Postgres_To_GCS
[2024-01-07T19:58:51.669+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:58:51.833+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T19:58:51.851+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:58:51.878+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:58:51.901+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:58:51.911+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:58:51.948+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T19:58:51.956+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T19:58:53.924+0000] {gcs.py:576} INFO - Data stream uploaded to data/country.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T19:58:53.939+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T19:58:53.986+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:58:54.006+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T19:58:54.007+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:58:54.035+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T195851, end_date=20240107T195854
[2024-01-07T19:58:54.196+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:58:54.241+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T20:18:37.891+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T20:18:38.018+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T20:18:38.020+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T20:18:38.120+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T20:18:38.131+0000] {standard_task_runner.py:57} INFO - Started process 11218 to run task
[2024-01-07T20:18:38.135+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '468', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpjkv7slvx']
[2024-01-07T20:18:38.139+0000] {standard_task_runner.py:85} INFO - Job 468: Subtask copy_country_Postgres_To_GCS
[2024-01-07T20:18:38.271+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T20:18:38.459+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T20:18:38.481+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:18:38.503+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:18:38.541+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T20:18:38.636+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T20:18:38.644+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T20:18:40.705+0000] {gcs.py:700} INFO - Blob data/country.parquet deleted.
[2024-01-07T20:18:40.750+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T20:18:40.843+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:18:40.879+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T20:18:40.903+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T201838, end_date=20240107T201840
[2024-01-07T20:18:41.022+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T20:18:41.089+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T20:59:23.698+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T20:59:23.730+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T20:59:23.730+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T20:59:23.771+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T20:59:23.782+0000] {standard_task_runner.py:57} INFO - Started process 12303 to run task
[2024-01-07T20:59:23.788+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '483', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpeee6wkhd']
[2024-01-07T20:59:23.793+0000] {standard_task_runner.py:85} INFO - Job 483: Subtask copy_country_Postgres_To_GCS
[2024-01-07T20:59:23.968+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T20:59:24.154+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T20:59:24.175+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:59:24.201+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:59:24.226+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T20:59:24.275+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T20:59:24.288+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T20:59:26.330+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet
[2024-01-07T20:59:26.524+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T205923, end_date=20240107T205926
[2024-01-07T20:59:26.545+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T20:59:26.547+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T20:59:26.547+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T20:59:26.563+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T20:59:26.565+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T20:59:26.569+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T20:59:26.617+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 483 for task copy_country_Postgres_To_GCS (404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet; 12303)
[2024-01-07T20:59:26.676+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T20:59:26.782+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T21:10:20.507+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:10:20.522+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:10:20.523+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T21:10:20.567+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T21:10:20.599+0000] {standard_task_runner.py:57} INFO - Started process 12610 to run task
[2024-01-07T21:10:20.605+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '500', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpax23rggd']
[2024-01-07T21:10:20.610+0000] {standard_task_runner.py:85} INFO - Job 500: Subtask copy_country_Postgres_To_GCS
[2024-01-07T21:10:20.717+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T21:10:20.868+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T21:10:20.896+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:10:20.919+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:10:20.964+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T21:10:21.005+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T21:10:21.034+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T21:10:23.356+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet
[2024-01-07T21:10:23.395+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T211020, end_date=20240107T211023
[2024-01-07T21:10:23.421+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T21:10:23.423+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:10:23.424+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:10:23.446+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:10:23.447+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:10:23.447+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T21:10:23.490+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 500 for task copy_country_Postgres_To_GCS (404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet; 12610)
[2024-01-07T21:10:23.518+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T21:10:23.546+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T21:22:45.620+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:22:45.720+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:22:45.720+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T21:22:45.915+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T21:22:45.926+0000] {standard_task_runner.py:57} INFO - Started process 278 to run task
[2024-01-07T21:22:45.931+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '532', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpxecj_0ym']
[2024-01-07T21:22:45.935+0000] {standard_task_runner.py:85} INFO - Job 532: Subtask copy_country_Postgres_To_GCS
[2024-01-07T21:22:46.045+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 6609460de6e5
[2024-01-07T21:22:46.226+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T21:22:46.245+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:22:46.266+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:22:46.469+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T21:22:47.102+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T21:22:47.114+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T21:22:49.532+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet
[2024-01-07T21:22:49.622+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T212245, end_date=20240107T212249
[2024-01-07T21:22:49.646+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T21:22:49.649+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:22:49.649+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:22:49.667+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:22:49.667+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:22:49.668+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T21:22:49.758+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 532 for task copy_country_Postgres_To_GCS (404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet; 278)
[2024-01-07T21:22:49.805+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T21:22:49.847+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T21:34:05.577+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:34:05.649+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:34:05.649+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T21:34:05.692+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T21:34:05.707+0000] {standard_task_runner.py:57} INFO - Started process 601 to run task
[2024-01-07T21:34:05.712+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '547', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpznrv3g9w']
[2024-01-07T21:34:05.715+0000] {standard_task_runner.py:85} INFO - Job 547: Subtask copy_country_Postgres_To_GCS
[2024-01-07T21:34:05.858+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 6609460de6e5
[2024-01-07T21:34:06.482+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T21:34:06.511+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:34:06.528+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:34:06.689+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T21:34:06.773+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T21:34:06.780+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T21:34:09.974+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 63, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet
[2024-01-07T21:34:10.118+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T213405, end_date=20240107T213410
[2024-01-07T21:34:10.150+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T21:34:10.153+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:34:10.154+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:34:10.177+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:34:10.177+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:34:10.177+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 63, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T21:34:10.355+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 547 for task copy_country_Postgres_To_GCS (404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcountry.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/country.parquet; 601)
[2024-01-07T21:34:10.400+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T21:34:10.444+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
