[2023-12-01T11:47:01.107+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_to_gcs_bucket.PostgresToGCS1 scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2023-12-01T11:47:01.116+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_to_gcs_bucket.PostgresToGCS1 scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2023-12-01T11:47:01.117+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-12-01T11:47:01.174+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): PostgresToGCS1> on 2023-11-29 00:00:00+00:00
[2023-12-01T11:47:01.180+0000] {standard_task_runner.py:57} INFO - Started process 1309 to run task
[2023-12-01T11:47:01.184+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_to_gcs_bucket', 'PostgresToGCS1', 'scheduled__2023-11-29T00:00:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp2nldpxll']
[2023-12-01T11:47:01.186+0000] {standard_task_runner.py:85} INFO - Job 214: Subtask PostgresToGCS1
[2023-12-01T11:47:01.260+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_to_gcs_bucket.PostgresToGCS1 scheduled__2023-11-29T00:00:00+00:00 [running]> on host 363088228d6a
[2023-12-01T11:47:01.416+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ingest_to_gcs_bucket' AIRFLOW_CTX_TASK_ID='PostgresToGCS1' AIRFLOW_CTX_EXECUTION_DATE='2023-11-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-29T00:00:00+00:00'
[2023-12-01T11:47:01.431+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-01T11:47:01.435+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-12-01T11:47:01.450+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2023-12-01T11:47:01.472+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2023-12-01T11:47:01.563+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 37, in Postgres_To_GCS1
    with open(table +'.csv', 'w') as fp:
PermissionError: [Errno 13] Permission denied: 'course.csv'
[2023-12-01T11:47:01.580+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_to_gcs_bucket, task_id=PostgresToGCS1, execution_date=20231129T000000, start_date=20231201T114701, end_date=20231201T114701
[2023-12-01T11:47:01.611+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-12-01T11:47:01.612+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2023-12-01T11:47:01.612+0000] {email.py:270} INFO - Email alerting: attempt 1
[2023-12-01T11:47:01.639+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2023-12-01T11:47:01.639+0000] {email.py:270} INFO - Email alerting: attempt 1
[2023-12-01T11:47:01.640+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 37, in Postgres_To_GCS1
    with open(table +'.csv', 'w') as fp:
PermissionError: [Errno 13] Permission denied: 'course.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-12-01T11:47:01.710+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 214 for task PostgresToGCS1 ([Errno 13] Permission denied: 'course.csv'; 1309)
[2023-12-01T11:47:01.757+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T11:47:01.811+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-01T12:53:19.723+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_to_gcs_bucket.PostgresToGCS1 scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2023-12-01T12:53:19.755+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_to_gcs_bucket.PostgresToGCS1 scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2023-12-01T12:53:19.755+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-12-01T12:53:19.784+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): PostgresToGCS1> on 2023-11-29 00:00:00+00:00
[2023-12-01T12:53:19.791+0000] {standard_task_runner.py:57} INFO - Started process 1330 to run task
[2023-12-01T12:53:19.795+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_to_gcs_bucket', 'PostgresToGCS1', 'scheduled__2023-11-29T00:00:00+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpjbmfjbzk']
[2023-12-01T12:53:19.798+0000] {standard_task_runner.py:85} INFO - Job 238: Subtask PostgresToGCS1
[2023-12-01T12:53:19.869+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_to_gcs_bucket.PostgresToGCS1 scheduled__2023-11-29T00:00:00+00:00 [running]> on host 40ff33dd73db
[2023-12-01T12:53:20.018+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ingest_to_gcs_bucket' AIRFLOW_CTX_TASK_ID='PostgresToGCS1' AIRFLOW_CTX_EXECUTION_DATE='2023-11-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-29T00:00:00+00:00'
[2023-12-01T12:53:20.020+0000] {logging_mixin.py:151} INFO - Current working directory: /opt/airflow
[2023-12-01T12:53:20.040+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-01T12:53:20.042+0000] {base.py:73} INFO - Using connection ID 'google_cloud_conn' for task execution.
[2023-12-01T12:53:20.057+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2023-12-01T12:53:20.075+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2023-12-01T12:53:20.089+0000] {postgres_to_gcs_staging.py:42} INFO - Uploading to bucket, course.csv
[2023-12-01T12:53:21.765+0000] {gcs.py:562} INFO - File course.csv uploaded to course.csv in school_data_lake_data-warehousing-proj bucket
[2023-12-01T12:53:21.781+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-01T12:53:21.782+0000] {base.py:73} INFO - Using connection ID 'google_cloud_conn' for task execution.
[2023-12-01T12:53:21.797+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2023-12-01T12:53:21.812+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2023-12-01T12:53:21.826+0000] {postgres_to_gcs_staging.py:42} INFO - Uploading to bucket, country.csv
[2023-12-01T12:53:23.470+0000] {gcs.py:562} INFO - File country.csv uploaded to country.csv in school_data_lake_data-warehousing-proj bucket
[2023-12-01T12:53:23.485+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-01T12:53:23.486+0000] {base.py:73} INFO - Using connection ID 'google_cloud_conn' for task execution.
[2023-12-01T12:53:23.501+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2023-12-01T12:53:23.517+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2023-12-01T12:53:23.532+0000] {postgres_to_gcs_staging.py:42} INFO - Uploading to bucket, department.csv
[2023-12-01T12:53:25.199+0000] {gcs.py:562} INFO - File department.csv uploaded to department.csv in school_data_lake_data-warehousing-proj bucket
[2023-12-01T12:53:25.199+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-01T12:53:25.216+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_to_gcs_bucket, task_id=PostgresToGCS1, execution_date=20231129T000000, start_date=20231201T125319, end_date=20231201T125325
[2023-12-01T12:53:25.292+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-01T12:53:25.351+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
