[2024-01-07T13:54:14.065+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T13:54:14.081+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T13:54:14.081+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T13:54:14.118+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T13:54:14.129+0000] {standard_task_runner.py:57} INFO - Started process 1020 to run task
[2024-01-07T13:54:14.133+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp2yr5u8li']
[2024-01-07T13:54:14.136+0000] {standard_task_runner.py:85} INFO - Job 250: Subtask copy_course_Postgres_To_GCS
[2024-01-07T13:54:14.225+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T13:54:14.383+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T13:54:14.402+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:54:14.416+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:54:14.437+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T13:54:14.444+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T13:54:14.445+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T13:54:14.462+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T135414, end_date=20240107T135414
[2024-01-07T13:54:14.506+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T13:54:14.535+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T15:52:57.485+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:52:57.502+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:52:57.502+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T15:52:57.527+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T15:52:57.535+0000] {standard_task_runner.py:57} INFO - Started process 4264 to run task
[2024-01-07T15:52:57.541+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp1s92w8tx']
[2024-01-07T15:52:57.549+0000] {standard_task_runner.py:85} INFO - Job 355: Subtask copy_course_Postgres_To_GCS
[2024-01-07T15:52:57.642+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T15:52:57.790+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T15:52:57.807+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:52:57.823+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:52:57.847+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T15:52:57.854+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T15:52:57.894+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T15:52:57.903+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T15:52:59.998+0000] {gcs.py:576} INFO - Data stream uploaded to data/course-{ds_nodash}.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T15:53:00.017+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T15:53:00.105+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:53:00.129+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T15:53:00.130+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T15:53:00.161+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T155257, end_date=20240107T155300
[2024-01-07T15:53:00.219+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T15:53:00.249+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T15:58:23.278+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:58:23.298+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T15:58:23.299+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T15:58:23.328+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T15:58:23.338+0000] {standard_task_runner.py:57} INFO - Started process 4433 to run task
[2024-01-07T15:58:23.342+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpx_7ywup0']
[2024-01-07T15:58:23.349+0000] {standard_task_runner.py:85} INFO - Job 365: Subtask copy_course_Postgres_To_GCS
[2024-01-07T15:58:23.443+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T15:58:23.601+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T15:58:23.621+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:58:23.637+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:58:23.661+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T15:58:23.671+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T15:58:23.693+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    date = {{ ds_nodash }}
NameError: name 'ds_nodash' is not defined
[2024-01-07T15:58:23.720+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T155823, end_date=20240107T155823
[2024-01-07T15:58:23.741+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T15:58:23.742+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T15:58:23.742+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T15:58:23.756+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T15:58:23.756+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T15:58:23.757+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    date = {{ ds_nodash }}
NameError: name 'ds_nodash' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T15:58:23.904+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 365 for task copy_course_Postgres_To_GCS (name 'ds_nodash' is not defined; 4433)
[2024-01-07T15:58:23.919+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T15:58:23.944+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T16:05:56.737+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T16:05:56.794+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T16:05:56.795+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T16:05:56.858+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T16:05:56.865+0000] {standard_task_runner.py:57} INFO - Started process 4659 to run task
[2024-01-07T16:05:56.869+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '373', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpvhj24ns0']
[2024-01-07T16:05:56.875+0000] {standard_task_runner.py:85} INFO - Job 373: Subtask copy_course_Postgres_To_GCS
[2024-01-07T16:05:57.028+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T16:05:57.188+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T16:05:57.207+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:57.223+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:57.247+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T16:05:57.254+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T16:05:57.286+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T16:05:57.293+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T16:05:59.438+0000] {gcs.py:576} INFO - Data stream uploaded to data/course-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T16:05:59.451+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T16:05:59.479+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T16:05:59.493+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T16:05:59.494+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T16:05:59.511+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T160556, end_date=20240107T160559
[2024-01-07T16:05:59.571+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T16:05:59.601+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T17:53:16.286+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T17:53:16.310+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T17:53:16.311+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T17:53:16.340+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T17:53:16.348+0000] {standard_task_runner.py:57} INFO - Started process 7256 to run task
[2024-01-07T17:53:16.353+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '383', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmprcxikwxe']
[2024-01-07T17:53:16.357+0000] {standard_task_runner.py:85} INFO - Job 383: Subtask copy_course_Postgres_To_GCS
[2024-01-07T17:53:16.446+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T17:53:16.625+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T17:53:16.647+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T17:53:16.662+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T17:53:16.682+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T17:53:16.689+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T17:53:16.723+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T17:53:16.730+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T17:53:18.978+0000] {gcs.py:576} INFO - Data stream uploaded to data/course-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T17:53:18.996+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T17:53:19.022+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T17:53:19.041+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T17:53:19.042+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T17:53:19.062+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T175316, end_date=20240107T175319
[2024-01-07T17:53:19.145+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T17:53:19.178+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T18:01:22.515+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T18:01:22.536+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T18:01:22.536+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T18:01:22.567+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T18:01:22.575+0000] {standard_task_runner.py:57} INFO - Started process 7496 to run task
[2024-01-07T18:01:22.591+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpey8sb8oa']
[2024-01-07T18:01:22.601+0000] {standard_task_runner.py:85} INFO - Job 394: Subtask copy_course_Postgres_To_GCS
[2024-01-07T18:01:22.903+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T18:01:23.375+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T18:01:23.396+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T18:01:23.412+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T18:01:23.434+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T18:01:23.440+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T18:01:23.514+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T18:01:23.522+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T18:01:25.674+0000] {gcs.py:576} INFO - Data stream uploaded to data/course-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T18:01:25.686+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T18:01:25.714+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T18:01:25.727+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T18:01:25.728+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T18:01:25.744+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T180122, end_date=20240107T180125
[2024-01-07T18:01:25.852+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T18:01:25.875+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:12:27.409+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:12:27.544+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:12:27.544+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:12:27.625+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T19:12:27.633+0000] {standard_task_runner.py:57} INFO - Started process 9371 to run task
[2024-01-07T19:12:27.637+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '411', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp1rc_kox0']
[2024-01-07T19:12:27.640+0000] {standard_task_runner.py:85} INFO - Job 411: Subtask copy_course_Postgres_To_GCS
[2024-01-07T19:12:27.845+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:12:28.179+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T19:12:28.198+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:12:28.213+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:12:28.238+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:12:28.249+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T19:12:28.250+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:12:28.273+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T191227, end_date=20240107T191228
[2024-01-07T19:12:28.691+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:12:28.911+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:13:42.217+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:13:42.245+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:13:42.245+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:13:42.278+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T19:13:42.284+0000] {standard_task_runner.py:57} INFO - Started process 9431 to run task
[2024-01-07T19:13:42.287+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '420', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpg4yhqf3h']
[2024-01-07T19:13:42.290+0000] {standard_task_runner.py:85} INFO - Job 420: Subtask copy_course_Postgres_To_GCS
[2024-01-07T19:13:42.403+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:13:42.564+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T19:13:42.579+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:13:42.592+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:13:42.611+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:13:42.633+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T19:13:43.161+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T19:13:43.167+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T19:13:45.145+0000] {gcs.py:576} INFO - Data stream uploaded to data/course-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T19:13:45.158+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T19:13:45.181+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:13:45.196+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T19:13:45.197+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:13:45.219+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T191342, end_date=20240107T191345
[2024-01-07T19:13:45.277+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:13:45.308+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:30:41.156+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:30:41.186+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:30:41.186+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:30:41.220+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T19:30:41.228+0000] {standard_task_runner.py:57} INFO - Started process 9936 to run task
[2024-01-07T19:30:41.232+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '439', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpzyms2824']
[2024-01-07T19:30:41.236+0000] {standard_task_runner.py:85} INFO - Job 439: Subtask copy_course_Postgres_To_GCS
[2024-01-07T19:30:41.323+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:30:41.459+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T19:30:41.477+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:30:41.490+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:30:41.511+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:30:41.517+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T19:30:41.547+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T19:30:41.553+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T19:30:43.444+0000] {gcs.py:576} INFO - Data stream uploaded to data/course-20240105.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T19:30:43.461+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T19:30:43.479+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:30:43.491+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T19:30:43.491+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:30:43.511+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T193041, end_date=20240107T193043
[2024-01-07T19:30:43.616+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:30:43.639+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T19:58:40.048+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:58:40.072+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T19:58:40.074+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T19:58:40.099+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T19:58:40.112+0000] {standard_task_runner.py:57} INFO - Started process 10678 to run task
[2024-01-07T19:58:40.117+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '455', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp86wi7y67']
[2024-01-07T19:58:40.122+0000] {standard_task_runner.py:85} INFO - Job 455: Subtask copy_course_Postgres_To_GCS
[2024-01-07T19:58:40.239+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T19:58:40.456+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T19:58:40.483+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:58:40.506+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:58:40.545+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T19:58:40.585+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T19:58:41.184+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T19:58:41.191+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T19:58:43.275+0000] {gcs.py:576} INFO - Data stream uploaded to data/course.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T19:58:43.293+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T19:58:43.373+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T19:58:43.500+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, course
[2024-01-07T19:58:43.500+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T19:58:43.527+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T195840, end_date=20240107T195843
[2024-01-07T19:58:43.609+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T19:58:43.715+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T20:18:37.934+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T20:18:38.012+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T20:18:38.013+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T20:18:38.087+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T20:18:38.095+0000] {standard_task_runner.py:57} INFO - Started process 11217 to run task
[2024-01-07T20:18:38.099+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '469', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpcx6y96n1']
[2024-01-07T20:18:38.104+0000] {standard_task_runner.py:85} INFO - Job 469: Subtask copy_course_Postgres_To_GCS
[2024-01-07T20:18:38.238+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T20:18:38.424+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T20:18:38.446+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:18:38.470+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:18:38.503+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T20:18:38.610+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T20:18:38.624+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T20:18:40.701+0000] {gcs.py:700} INFO - Blob data/course.parquet deleted.
[2024-01-07T20:18:40.734+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T20:18:40.805+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:18:40.829+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T20:18:40.866+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T201837, end_date=20240107T201840
[2024-01-07T20:18:40.981+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T20:18:41.044+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T20:59:23.723+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T20:59:23.744+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T20:59:23.745+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T20:59:23.794+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T20:59:23.807+0000] {standard_task_runner.py:57} INFO - Started process 12304 to run task
[2024-01-07T20:59:23.813+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '484', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpo6p3qawc']
[2024-01-07T20:59:23.821+0000] {standard_task_runner.py:85} INFO - Job 484: Subtask copy_course_Postgres_To_GCS
[2024-01-07T20:59:23.979+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T20:59:24.158+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T20:59:24.186+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:59:24.205+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T20:59:24.232+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T20:59:24.272+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T20:59:24.283+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T20:59:26.330+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet
[2024-01-07T20:59:26.524+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T205923, end_date=20240107T205926
[2024-01-07T20:59:26.545+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T20:59:26.547+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T20:59:26.547+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T20:59:26.564+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T20:59:26.565+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T20:59:26.567+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T20:59:26.628+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 484 for task copy_course_Postgres_To_GCS (404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet; 12304)
[2024-01-07T20:59:26.666+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T20:59:26.756+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T21:10:20.521+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:10:20.536+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:10:20.536+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T21:10:20.578+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T21:10:20.599+0000] {standard_task_runner.py:57} INFO - Started process 12609 to run task
[2024-01-07T21:10:20.604+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '501', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpz5g4r1ju']
[2024-01-07T21:10:20.611+0000] {standard_task_runner.py:85} INFO - Job 501: Subtask copy_course_Postgres_To_GCS
[2024-01-07T21:10:20.717+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T21:10:20.885+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T21:10:20.939+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:10:20.977+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:10:21.027+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T21:10:21.084+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T21:10:21.102+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T21:10:23.356+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet
[2024-01-07T21:10:23.386+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T211020, end_date=20240107T211023
[2024-01-07T21:10:23.416+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T21:10:23.418+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:10:23.418+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:10:23.434+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:10:23.435+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:10:23.435+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T21:10:23.479+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 501 for task copy_course_Postgres_To_GCS (404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet; 12609)
[2024-01-07T21:10:23.515+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T21:10:23.570+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T21:22:45.634+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:22:45.718+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:22:45.718+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T21:22:45.915+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T21:22:45.926+0000] {standard_task_runner.py:57} INFO - Started process 279 to run task
[2024-01-07T21:22:45.933+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '533', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp200fd5q9']
[2024-01-07T21:22:45.936+0000] {standard_task_runner.py:85} INFO - Job 533: Subtask copy_course_Postgres_To_GCS
[2024-01-07T21:22:46.035+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 6609460de6e5
[2024-01-07T21:22:46.226+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T21:22:46.247+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:22:46.270+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:22:46.469+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T21:22:47.099+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T21:22:47.110+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T21:22:49.532+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet
[2024-01-07T21:22:49.620+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T212245, end_date=20240107T212249
[2024-01-07T21:22:49.646+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T21:22:49.648+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:22:49.649+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:22:49.663+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:22:49.663+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:22:49.664+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 62, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T21:22:49.713+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 533 for task copy_course_Postgres_To_GCS (404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet; 279)
[2024-01-07T21:22:49.768+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T21:22:49.795+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T21:34:05.573+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:34:05.649+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-01-07T21:34:05.649+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T21:34:05.682+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_course_Postgres_To_GCS> on 2024-01-05 00:00:00+00:00
[2024-01-07T21:34:05.693+0000] {standard_task_runner.py:57} INFO - Started process 600 to run task
[2024-01-07T21:34:05.697+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_course_Postgres_To_GCS', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '548', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpksa7sgat']
[2024-01-07T21:34:05.702+0000] {standard_task_runner.py:85} INFO - Job 548: Subtask copy_course_Postgres_To_GCS
[2024-01-07T21:34:06.009+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_course_Postgres_To_GCS scheduled__2024-01-05T00:00:00+00:00 [running]> on host 6609460de6e5
[2024-01-07T21:34:06.551+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_course_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-01-07T21:34:06.583+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:34:06.642+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T21:34:06.688+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T21:34:06.773+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T21:34:06.780+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T21:34:09.974+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 63, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet
[2024-01-07T21:34:10.116+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_course_Postgres_To_GCS, execution_date=20240105T000000, start_date=20240107T213405, end_date=20240107T213410
[2024-01-07T21:34:10.143+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T21:34:10.144+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:34:10.145+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:34:10.166+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T21:34:10.166+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T21:34:10.167+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 63, in Postgres_To_GCS_Bucket
    gcs_hook.delete(bucket_name=BUCKET, object_name=gcs_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 698, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 763, in delete
    self.bucket.delete_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 1647, in delete_blob
    client._delete_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 685, in _delete_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T21:34:10.330+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 548 for task copy_course_Postgres_To_GCS (404 DELETE https://storage.googleapis.com/storage/v1/b/school_data_lake_data-warehousing-proj/o/data%2Fcourse.parquet?prettyPrint=false: No such object: school_data_lake_data-warehousing-proj/data/course.parquet; 600)
[2024-01-07T21:34:10.377+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T21:34:10.422+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
